
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    // Schema-changing CLI commands (db push, migrate) hang against the transaction-mode
    // pgbouncer pooler on 6543 - route them through the direct/session connection instead.
    directUrl: env("DIRECT_URL"),
  },
});
